---
ee_list:
  - name: config_as_code_ee
    bindep:
      - unzip
    python:
      - ansible-lint
      - netaddr
    collections:
      - name: infra.controller_configuration
      - name: infra.ah_configuration
      - name: infra.ee_utilities
      - name: infra.aap_utilities
      - name: awx.awx
    append:
      - RUN dnf update -y
      # - RUN pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
...
