---
ah_token_username: token_user
ah_users:
  - username: token_user
    groups:
      - "admin"
    append: true
    is_superuser: true
    password: "{{ ah_token_password }}"
    state: "present"
...
