---
controller_inventory_sources_all:
  - name: rhel_edge_fleet_management_source
    organization: rhel_edge_fleet_management
    source: scm
    source_project: rhel_edge_fleet_management
    source_path: "inventory_{{ env }}.yml"
    inventory: rhel_edge_fleet_management
    credential: ""
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0
...
